# Generated by Django 5.2.13 on 2026-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_backfill_valid_pricing_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=128)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обработанное Stripe-событие',
                'verbose_name_plural': 'Обработанные Stripe-события',
                'ordering': ('-processed_at',),
            },
        ),
    ]
